WebReportes/Controllers/VentasController.cs
using Servicio;
using System.Collections.Generic;
using System.Web.Mvc;
using System.Linq;
using System;
using WebReportes.Helpers;
using WebReportes.Utils;

namespace WebReportes.Controllers
{

    [Authorize]
    public class VentasController : Controller
    {


        #region Ventas Local
            [HttpGet]
            [AuthorizeByRol]
            [MenuFilter]
            public ActionResult Local()
            {
                string Empresa = SessionEx.Get(SessionEx.eCommerce);

                Common commons = new Common();

                var sucursales = commons.SucursalesXEmpresa( Empresa );
                ViewBag.sucursales = sucursales.Select(i => new SelectListItem() { Value = i.Key, Text = i.Value }).ToList();

                ViewBag.anio = commons.ListaAnios();
                ViewBag.meses = commons.ListaMeses();

                return View();
            }


            [HttpPost]
            [AuthorizeByRol]
            public ActionResult Local(FormCollection form)
            {
                try
                {
                    string Empresa = SessionEx.Get(SessionEx.eCommerce);
                    int anio = 0;
                    string mes = "";
                    string sucursales = "";
                    bool descarga = false;

                    int.TryParse(form["anio"], out anio);
                    mes = form["mes"];
                    sucursales = form["sucursales"];
                    bool.TryParse(form["descarga"], out descarga);

                    using (Ventas ventas = new Ventas())
                    {
                        var data = ventas.Mes_Local( Empresa, anio, mes, sucursales);

                        if (descarga)
                        {
                            this.Response.AddHeader("content-type", "application/vnd.ms-excel");
                            this.Response.AddHeader("content-disposition", string.Format("inline;filename=Ventas_Local_{0}-{1}-{2}.xls",  Empresa ,anio, mes));
                        }

                        ViewBag.Descarga = descarga ? "Si" : "No";
                        return PartialView("Local_Resultado", data);
                    }


                }
                catch (Exception e)
                {

                }
                return PartialView("Error");
            }

        #endregion


        #region Ventas Local Acumuladas
        [HttpGet]
        [AuthorizeByRol]
        [MenuFilter]
        public ActionResult LocalAcumulada()
        {
            string Empresa = SessionEx.Get(SessionEx.eCommerce);

            Common commons = new Common();

            var sucursales = commons.SucursalesXEmpresa(Empresa);
            ViewBag.sucursales = sucursales.Select(i => new SelectListItem() { Value = i.Key, Text = i.Value }).ToList();

            ViewBag.anio = commons.ListaAnios();
            ViewBag.meses = commons.ListaMeses();

            return View("Local_Acumulado");

            // return View();
        }


        [HttpPost]
        [AuthorizeByRol]
        public ActionResult LocalAcumulada(FormCollection form)
        {
            try
            {
                string Empresa = SessionEx.Get(SessionEx.eCommerce);
                int anio = 0;
                string mes = "";
                string sucursales = "";
                bool descarga = false;

                int.TryParse(form["anio"], out anio);
                mes = form["mes"];
                sucursales = form["sucursales"];
                bool.TryParse(form["descarga"], out descarga);

                using (Ventas ventas = new Ventas())
                {
                    var data = ventas.Mes_Local(Empresa, anio, mes, sucursales);

                    if (descarga)
                    {
                        this.Response.AddHeader("content-type", "application/vnd.ms-excel");
                        this.Response.AddHeader("content-disposition", string.Format("inline;filename=Ventas_Local_Acumulada_{0}-{1}-{2}.xls", Empresa, anio, mes));
                    }

                    ViewBag.Descarga = descarga ? "Si" : "No";
                    return PartialView("Local_Acumulado_Resultado", data);
                }


            }
            catch (Exception e)
            {

            }
            return PartialView("Error");
        }


        #endregion


        #region Ventas Web
        [HttpGet]
        [AuthorizeByRol]
        [MenuFilter]
        public ActionResult Web()
        {
            string Empresa = SessionEx.Get(SessionEx.eCommerce);

            Common commons = new Common();

            var sucursales = commons.SucursalesXEmpresa(Empresa);
            ViewBag.sucursales = sucursales.Select(i => new SelectListItem() { Value = i.Key, Text = i.Value }).ToList();

            ViewBag.anio = commons.ListaAnios();
            ViewBag.meses = commons.ListaMeses();

            return View();
        }


        [HttpPost]
        [AuthorizeByRol]
        public ActionResult Web(FormCollection form)
        {
            try
            {
                string Empresa = SessionEx.Get(SessionEx.eCommerce);
                int anio = 0;
                string mes = "";
                string sucursales = "";
                bool descarga = false;

                int.TryParse(form["anio"], out anio);
                mes = form["mes"];
                sucursales = form["sucursales"];
                bool.TryParse(form["descarga"], out descarga);

                using (Ventas ventas = new Ventas())
                {
                    var data = ventas.Mes_Web(Empresa, anio, mes, sucursales);

                    if (descarga)
                    {
                        this.Response.AddHeader("content-type", "application/vnd.ms-excel");
                        this.Response.AddHeader("content-disposition", string.Format("inline;filename=Ventas_Web_{0}-{1}-{2}.xls", Empresa, anio, mes));
                    }

                    ViewBag.Descarga = descarga ? "Si" : "No";
                    return PartialView("Web_Resultado", data);
                }


            }
            catch (Exception e)
            {

            }
            return PartialView("Error");
        }
        #endregion


     
    
    }
}

WebReportes/Views/Ventas/Local.cshtml
<section class="form-fields">
    <fieldset>
        @using (@Html.BeginForm("Local", "Ventas", FormMethod.Post, new { name = "Info" }))
        {
            @Html.Hidden("descarga", "")
            @Html.Hidden("sucursales", "")
            <div class="fld-row">

                <div class="fld  col-md-2"> 
                    @Html.DropDownList("anio", (List<SelectListItem>)ViewBag.anio, new { @class = "chosen-select" , placeholder="Seleccionar Año", @default="2018"})
                </div>
                <div class="fld  col-md-2"> 
                    @Html.DropDownList("mes", (List<SelectListItem>)ViewBag.meses, new { @class = "chosen-select", placeholder = "Seleccionar Mes", @default="07" })
                </div>
                <div class="fld  col-md-4"> 
                    @Html.DropDownList("sucursales_list", (List<SelectListItem>)ViewBag.sucursales, new { @class= "chosen-select-multiple",  multiple = "multiple", resumeto="#sucursales" }) 
                </div>

                <div class="fld col-md-4">
                    <input type="button" name="clear" value="Limpiar Datos" class="form_clear" data-form="Info" data-response="#form_response" />
                    <input type="button" name="submit" value="Generar Reporte" class="form_submit" data-form="Info" data-response="#form_response" />
                    <input type="button" name="export" value="Exportar Resultados" class="form_export" data-form="Info" />
                    <input type="button" name="fullscreen" value="Fullscreen" class="toggle_fullscreen" />                    
                    <input type="submit" name="enviar" value="Enviar" class="form_enviar" style="display:none;" />
                </div>

                 
            </div>
        }

    </fieldset>
</section>
<section class="response_wrap_container">
    <div class="response_container">
        <div id="form_response"  ></div>
    </div>
</section>

WebReportes/Views/Ventas/Local_Acumulado.cshtml
<section class="form-fields">
    <fieldset>
        @using (@Html.BeginForm("LocalAcumulada", "Ventas", FormMethod.Post, new { name = "Info" }))
        {
            @Html.Hidden("descarga", "")
            @Html.Hidden("sucursales", "")
            <div class="fld-row">

                <div class="fld  col-md-2"> 
                    @Html.DropDownList("anio", (List<SelectListItem>)ViewBag.anio, new { @class = "chosen-select" , placeholder="Seleccionar Año", @default="2018"})
                </div>
                <div class="fld  col-md-2"> 
                    @Html.DropDownList("mes", (List<SelectListItem>)ViewBag.meses, new { @class = "chosen-select", placeholder = "Seleccionar Mes", @default="07" })
                </div>
                <div class="fld  col-md-4"> 
                    @Html.DropDownList("sucursales_list", (List<SelectListItem>)ViewBag.sucursales, new { @class= "chosen-select-multiple",  multiple = "multiple", resumeto="#sucursales" }) 
                </div>

                <div class="fld col-md-4">
                    <input type="button" name="clear" value="Limpiar Datos" class="form_clear" data-form="Info" data-response="#form_response" />
                    <input type="button" name="submit" value="Generar Reporte" class="form_submit" data-form="Info" data-response="#form_response" />
                    <input type="button" name="export" value="Exportar Resultados" class="form_export" data-form="Info" />
                    <input type="button" name="fullscreen" value="Fullscreen" class="toggle_fullscreen" />                    
                    <input type="submit" name="enviar" value="Enviar" class="form_enviar" style="display:none;" />
                </div>

                 
            </div>
        }

    </fieldset>
</section>
<section class="response_wrap_container">
    <div class="response_container">
        <div id="form_response"  ></div>
    </div>
</section>

WebReportes/Views/Ventas/Microplay_Mes.cshtml
<section class="form-fields">
    <fieldset>
        @using (@Html.BeginForm("Microplay_Mes", "Ventas", FormMethod.Post, new { name = "Info" }))
        {
            @Html.Hidden("descarga", "")
            @Html.Hidden("sucursales", "")
            <div class="fld-row">

                <div class="fld  col-md-2"> 
                    @Html.DropDownList("anio", (List<SelectListItem>)ViewBag.anio, new { @class = "chosen-select" , placeholder="Seleccionar Año", @default="2018"})
                </div>
                <div class="fld  col-md-2"> 
                    @Html.DropDownList("mes", (List<SelectListItem>)ViewBag.meses, new { @class = "chosen-select", placeholder = "Seleccionar Mes", @default="07" })
                </div>
                <div class="fld  col-md-4"> 
                    @Html.DropDownList("sucursales_list", (List<SelectListItem>)ViewBag.sucursales, new { @class= "chosen-select-multiple",  multiple = "multiple", resumeto="#sucursales" }) 
                </div>

                <div class="fld col-md-4">
                    <input type="button" name="clear" value="Limpiar Datos" class="form_clear" data-form="Info" data-response="#form_response" />
                    <input type="button" name="submit" value="Generar Reporte" class="form_submit" data-form="Info" data-response="#form_response" />
                    <input type="button" name="export" value="Exportar Resultados" class="form_export" data-form="Info" />
                    <input type="button" name="fullscreen" value="Fullscreen" class="toggle_fullscreen" />                    
                    <input type="submit" name="enviar" value="Enviar" class="form_enviar" style="display:none;" />
                </div>

                 
            </div>
        }

    </fieldset>
</section>
<section class="response_wrap_container">
    <div class="response_container">
        <div id="form_response"  ></div>
    </div>
</section>

WebReportes/Views/Ventas/Microplay_Mes_Resultado.cshtml
@model IEnumerable<Dictionary<string,string>>

@if (Model.Count() == 0)
{
    <div class=""> No hay resultados disponibles.</div>
}
else
{

    var titulos = Model.First();
    var datos = Model.Skip(1).ToList();

    var totales = datos.Last();
    var total = totales.Where(w => w.Key.Contains("TOTALES"));


    var tiendas = titulos.Where(w => w.Key.Contains("_")).Select(n => n.Value.Split('_')[0]).Distinct();
    var anios = titulos.Where(w => w.Key.Contains("_") && !w.Key.Contains("VAR")).Select(n => n.Key.Split('_')[1]).Distinct();
    int tr_par = 1, td_par = 1;
    var useclass = "";


    <table border="1" class="table-resumida">

            <tr class="btn-info">
                <th align="center" colspan="1">  <p>D&iacute;a </p> </th>
                @foreach (var tienda in tiendas)
                {
                        <th align="center"  > <p>  @Html.Raw(tienda) </p> </th>
                }
            </tr>


            @foreach (var row in datos)
            {
                if (row.Count() > 1)
                {

                    useclass = (tr_par++ % 2 == 0 ? "par" : "impar");
                    int _dia = 0;
                    int.TryParse(row["dia"], out _dia);
                    if ( _dia < 1 ||  _dia > 31)
                    {
                        useclass = useclass + " totales";
                    }

                    <tr @Html.Raw("class='" + useclass + "'")>

                        <td align="right">  @Html.Raw(string.IsNullOrEmpty(row["dia"]) ? "TOTALES"  : row["dia"] ) </td>
                        @{ td_par = 1;}
                        @foreach (var tienda in tiendas)
                        {
                            var tActual = "";
                            useclass = "";

                            if (tienda.Equals("TOTALES") || tienda.Equals("ACUMULADO"))
                            {
                                useclass = "col_" + tienda.ToLower();
                            }
                            else
                            {
                                if (_dia >= 1 && _dia <= 31)
                                {
                                    useclass = "col_" + td_par.ToString() + " " + (td_par++ % 2 == 0 ? "par" : "impar");
                                }
                            }

                            try
                            {
                                tActual = row[tienda + "_" + anios.Skip(1).First()];
                            }
                            catch (Exception e)
                            {
                            }



                            <td align="right" @Html.Raw("class='Number " + useclass + "'")>  @Html.Raw(tActual) </td>

                        }
                    </tr>

                }
            }


    </table>
}

WebReportes/Views/Ventas/Microplay_Resultado.cshtml
@model IEnumerable<Dictionary<string,string>>

@if (Model.Count() == 0)
{
    <div class=""> No hay resultados disponibles.</div>
}
else
{

    var titulos = Model.First();
    var datos = Model.Skip(1).ToList();

    var totales = datos.Last();
    var total = totales.Where(w => w.Key.Contains("TOTALES"));


    var tiendas = titulos.Where(w => w.Key.Contains("_")).Select(n => n.Value.Split('_')[0]).Distinct();
    var anios = titulos.Where(w => w.Key.Contains("TOTALES_") && !w.Key.Contains("VAR")).Select(n => n.Key.Split('_')[1]).Distinct();
    int tr_par = 1, td_par = 1;
    var useclass = "";


    <table border="1" class="table-resumida">

            <tr>
                <th align="center" colspan="1">   </th>
                @foreach (var tienda in tiendas)
                {
                    if (tienda.Equals("TOTALES") || tienda.Equals("ACUMULADO"))
                    {
                        useclass = "vacio";
                        <th align="center" colspan="4" @Html.Raw("class='" + useclass + "'")>  @Html.Raw(tienda) </th>
                    }
                    else
                    {
                        useclass = "col_" + td_par.ToString() + " " + (td_par++ % 2 == 0 ? "par" : "impar");
                        <th align="center" colspan="3" @Html.Raw("class='" + useclass + "'")>  @Html.Raw(tienda) </th>
                    }

                }
            </tr>

            <tr class="btn-info">
                    @foreach (var col in titulos)
                    {
                        if (!col.Value.Contains("_ACUM") || col.Value.Contains("TOTALES") || col.Value.Contains("ACUMULADO"))
                        {
                            if (!col.Value.EndsWith("VAR") || (col.Value.EndsWith("VAR") && (col.Value.Contains("TOTALES") || col.Value.Contains("ACUMULADO"))))
                            {
                                if (col.Value.Contains("_"))
                                {
                                    <th align="center"> <p> @Html.Raw(col.Value.Split('_')[1]) </p> </th>
                                }
                                else
                                {
                                    <th align="center">  <p> @Html.Raw(col.Value) </p> </th>
                                }
                            }
                        }
                    }
            </tr>



            @foreach (var row in datos)
            {
                if (row.Count() > 1)
                {

                    useclass = (tr_par++ % 2 == 0 ? "par" : "impar");
                    int _dia = 0;
                    int.TryParse(row["dia"], out _dia);
                    if ( _dia < 1 ||  _dia > 31)
                    {
                        useclass = useclass + " totales";
                    }

                    <tr @Html.Raw("class='" + useclass + "'")>
                        @*<td align="right">  @Html.Raw(row["mes"]) </td>*@
                        <td align="right">  @Html.Raw(string.IsNullOrEmpty(row["dia"]) ? "TOTALES"  : row["dia"] ) </td>
                        @{ td_par = 1;}
                        @foreach (var tienda in tiendas)
                        {
                            var tActual = "";
                            var tAnterior = "";
                            var tVariacion = "";
                            var tVariacionP = "";

                            if (tienda.Equals("TOTALES") || tienda.Equals("ACUMULADO"))
                            {
                                useclass = "col_" + tienda.ToLower();
                            }
                            else
                            {
                                useclass = "col_" + td_par.ToString() + " " + (td_par++ % 2 == 0 ? "par" : "impar");
                            }

                            try
                            {
                                tActual = row[tienda + "_" + anios.First()];
                            }
                            catch (Exception e)
                            {
                            }

                            try
                            {
                                tAnterior = row[tienda + "_" + anios.Skip(1).First()];
                            }
                            catch (Exception e)
                            {
                            }

                            try
                            {
                                tVariacion = row[tienda + "_VAR"];
                            }
                            catch (Exception e)
                            {
                            }
                            try
                            {
                                tVariacionP = row[tienda + "_VARP"];
                            }
                            catch (Exception e)
                            {
                            }

                            <td align="right" @Html.Raw("class='Number " + useclass + "'")>  @Html.Raw(tActual) </td>
                            <td align="right" @Html.Raw("class='Number " + useclass + "'")>  @Html.Raw(tAnterior) </td>
                            if (tienda.Equals("TOTALES") || tienda.Equals("ACUMULADO"))
                            {
                            <td align="right" @Html.Raw("class='Number " + useclass + "'")>  @Html.Raw(tVariacion) </td>
                            }
                            <td align="right" @Html.Raw("class='Percent " + useclass + "'")>  @Html.Raw(tVariacionP) </td>
                        }
                    </tr>

                }
            }

        <tr class="totales">
            <td> % </td>
            @{
                double t0 = 0, t1 = 0;
                double.TryParse(totales["TOTALES_" + anios.First()], out t0);
                double.TryParse(totales["TOTALES_" + anios.Skip(1).First()], out t1);

            }
            @foreach (var tienda in tiendas.Where( w => !w.Contains("TOTALES") && ! w.Contains("ACUMULADO")))
            {
                double p0=0, p1=0;
                double.TryParse(totales[tienda + '_' + anios.First()], out p0);
                double.TryParse(totales[tienda + '_' + anios.Skip(1).First()], out p1);

                <td class="Percent">@Html.Raw(string.Format("{0:0.00}", (t0 == 0 ? 0 : p0 / t0 * 100)) )</td>
                <td class="Percent">@Html.Raw(string.Format("{0:0.00}", (t1 == 0 ? 0 : p1 / t1 * 100)) )</td>
                <td></td>
            }
            <td></td>
            <td></td>
            <td></td>
            <td></td>

            <td></td>
            <td></td>
            <td></td>
            <td></td>


        </tr>
    </table>
}

WebReportes/Views/Ventas/Web.cshtml
<section class="form-fields">
    <fieldset>
        @using (@Html.BeginForm("Web", "Ventas", FormMethod.Post, new { name = "Info" }))
        {
            @Html.Hidden("descarga", "")
            @Html.Hidden("sucursales", "")
            <div class="fld-row">

                <div class="fld  col-md-2"> 
                    @Html.DropDownList("anio", (List<SelectListItem>)ViewBag.anio, new { @class = "chosen-select" , placeholder="Seleccionar Año", @default="2018"})
                </div>
                <div class="fld  col-md-2"> 
                    @Html.DropDownList("mes", (List<SelectListItem>)ViewBag.meses, new { @class = "chosen-select", placeholder = "Seleccionar Mes", @default="07" })
                </div>
                <div class="fld  col-md-4"> 
                    @Html.DropDownList("sucursales_list", (List<SelectListItem>)ViewBag.sucursales, new { @class= "chosen-select-multiple",  multiple = "multiple", resumeto="#sucursales" }) 
                </div>

                <div class="fld col-md-4">
                    <input type="button" name="clear" value="Limpiar Datos" class="form_clear" data-form="Info" data-response="#form_response" />
                    <input type="button" name="submit" value="Generar Reporte" class="form_submit" data-form="Info" data-response="#form_response" />
                    <input type="button" name="export" value="Exportar Resultados" class="form_export" data-form="Info" />
                    <input type="button" name="fullscreen" value="Fullscreen" class="toggle_fullscreen" />                    
                    <input type="submit" name="enviar" value="Enviar" class="form_enviar" style="display:none;" />
                </div>

                 
            </div>
        }

    </fieldset>
</section>
<section class="response_wrap_container">
    <div class="response_container">
        <div id="form_response"  ></div>
    </div>
</section>

WebReportes/Views/Ventas/Web_Microplay.cshtml
<section class="form-fields">
    <fieldset>
        @using (@Html.BeginForm("Web_Microplay", "Ventas", FormMethod.Post, new { name = "Info" }))
        {
            @Html.Hidden("descarga", "")
            @Html.Hidden("sucursales", "")
            <div class="fld-row">

                <div class="fld  col-md-2"> 
                    @Html.DropDownList("anio", (List<SelectListItem>)ViewBag.anio, new { @class = "chosen-select" , placeholder="Seleccionar Año", @default="2018"})
                </div>
                <div class="fld  col-md-2"> 
                    @Html.DropDownList("mes", (List<SelectListItem>)ViewBag.meses, new { @class = "chosen-select", placeholder = "Seleccionar Mes", @default="07" })
                </div>
                <div class="fld  col-md-4"> 
                    @Html.DropDownList("sucursales_list", (List<SelectListItem>)ViewBag.sucursales, new { @class= "chosen-select-multiple",  multiple = "multiple", resumeto="#sucursales" }) 
                </div>

                <div class="fld col-md-4">
                    <input type="button" name="clear" value="Limpiar Datos" class="form_clear" data-form="Info" data-response="#form_response" />
                    <input type="button" name="submit" value="Generar Reporte" class="form_submit" data-form="Info" data-response="#form_response" />
                    <input type="button" name="export" value="Exportar Resultados" class="form_export" data-form="Info" />
                    <input type="button" name="fullscreen" value="Fullscreen" class="toggle_fullscreen" />                    
                    <input type="submit" name="enviar" value="Enviar" class="form_enviar" style="display:none;" />
                </div>

                 
            </div>
        }

    </fieldset>
</section>
<section class="response_wrap_container">
    <div class="response_container">
        <div id="form_response"  ></div>
    </div>
</section>

WebReportes/Views/Ventas/Web_Whittard.cshtml
<section class="form-fields">
    <fieldset>
        @using (@Html.BeginForm("Web_Whittard", "Ventas", FormMethod.Post, new { name = "Info" }))
        {
            @Html.Hidden("descarga", "")
            @Html.Hidden("sucursales", "")
            <div class="fld-row">

                <div class="fld  col-md-2"> 
                    @Html.DropDownList("anio", (List<SelectListItem>)ViewBag.anio, new { @class = "chosen-select" , placeholder="Seleccionar Año", @default="2018"})
                </div>
                <div class="fld  col-md-2"> 
                    @Html.DropDownList("mes", (List<SelectListItem>)ViewBag.meses, new { @class = "chosen-select", placeholder = "Seleccionar Mes", @default="07" })
                </div>
                <div class="fld  col-md-4"> 
                    @Html.DropDownList("sucursales_list", (List<SelectListItem>)ViewBag.sucursales, new { @class= "chosen-select-multiple",  multiple = "multiple", resumeto="#sucursales" }) 
                </div>

                <div class="fld col-md-4">
                    <input type="button" name="clear" value="Limpiar Datos" class="form_clear" data-form="Info" data-response="#form_response" />
                    <input type="button" name="submit" value="Generar Reporte" class="form_submit" data-form="Info" data-response="#form_response" />
                    <input type="button" name="export" value="Exportar Resultados" class="form_export" data-form="Info" />
                    <input type="button" name="fullscreen" value="Fullscreen" class="toggle_fullscreen" />                    
                    <input type="submit" name="enviar" value="Enviar" class="form_enviar" style="display:none;" />
                </div>

                 
            </div>
        }

    </fieldset>
</section>
<section class="response_wrap_container">
    <div class="response_container">
        <div id="form_response"  ></div>
    </div>
</section>

WebReportes/Views/Ventas/Whittard_Mes.cshtml
<section class="form-fields">
    <fieldset>
        @using (@Html.BeginForm("Whittard_Mes", "Ventas", FormMethod.Post, new { name = "Info" }))
        {
            @Html.Hidden("descarga", "")
            @Html.Hidden("sucursales", "")
            <div class="fld-row">

                <div class="fld  col-md-2"> 
                    @Html.DropDownList("anio", (List<SelectListItem>)ViewBag.anio, new { @class = "chosen-select" , placeholder="Seleccionar Año", @default="2018"})
                </div>
                <div class="fld  col-md-2"> 
                    @Html.DropDownList("mes", (List<SelectListItem>)ViewBag.meses, new { @class = "chosen-select", placeholder = "Seleccionar Mes", @default="07" })
                </div>
                <div class="fld  col-md-4"> 
                    @Html.DropDownList("sucursales_list", (List<SelectListItem>)ViewBag.sucursales, new { @class= "chosen-select-multiple",  multiple = "multiple", resumeto="#sucursales" }) 
                </div>

                <div class="fld col-md-4">
                    <input type="button" name="clear" value="Limpiar Datos" class="form_clear" data-form="Info" data-response="#form_response" />
                    <input type="button" name="submit" value="Generar Reporte" class="form_submit" data-form="Info" data-response="#form_response" />
                    <input type="button" name="export" value="Exportar Resultados" class="form_export" data-form="Info" />
                    <input type="button" name="fullscreen" value="Fullscreen" class="toggle_fullscreen" />                    
                    <input type="submit" name="enviar" value="Enviar" class="form_enviar" style="display:none;" />
                </div>

                 
            </div>
        }

    </fieldset>
</section>
<section class="response_wrap_container">
    <div class="response_container">
        <div id="form_response"  ></div>
    </div>
</section>