WebReportes/Areas/Api/Controllers/LocalesController.cs
using Servicio;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebReportes.Controllers;
using WebReportes.Utils;

namespace WebReportes.Areas.Api.Controllers
{


    public class Vendedor
    {
        public string id { get; set; }
        public string label { get; set; }
        public string value { get; set; }
    }


    [Authorize]
    public class LocalesController : Controller
    {

        [HttpGet]
        public JsonResult Vendedores( string term)
        {
            string Empresa = SessionEx.Get(SessionEx.eCommerce);

            List<Vendedor> ret = new List<Vendedor>();

            using (RrHh ventas = new RrHh())
            {
                var data = ventas.Vendedores(Empresa, term);
                foreach (var row in data)
                {
                    ret.Add(new Vendedor() { id = row["id"], label = row["label"], value = row["value"] });
                }
            }
            return Json(ret, JsonRequestBehavior.AllowGet);
        }

    }
}

WebReportes/Controllers/LocalesController.cs
using Servicio;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebReportes.Helpers;
using WebReportes.Utils;

namespace WebReportes.Controllers
{

    [Authorize]
    public class LocalesController : Controller
    {


        [HttpGet]
        [AuthorizeByRol]
        [MenuFilter]
        public ActionResult VentasPorVendedor()
        {
            string Empresa = SessionEx.Get(SessionEx.eCommerce);
            Common commons = new Common();

            string vendedor = User_Helper.FlexUserName();

            ViewBag.locales = commons.SucursalesXUsuario(vendedor).Select(i => new SelectListItem() { Value = i.Key, Text = i.Value }).ToList();

            ViewBag.anio = commons.ListaAnios();
            ViewBag.meses = commons.ListaMeses();
            return View();
        }


        [HttpPost]
        [AuthorizeByRol]
        public ActionResult VentasPorVendedor(FormCollection form)
        {
            try
            {
                string Empresa = SessionEx.Get(SessionEx.eCommerce);
                string vendedor = User_Helper.FlexUserName();

                string local = "";
                int anio = 0;
                string mes = "";
                bool descarga = false;

                int.TryParse(form["anio"], out anio);
                mes = form["mes"];
                bool.TryParse(form["descarga"], out descarga);
                local = form["local"];

                Common commons = new Common();
                var locales = commons.SucursalesXUsuario(vendedor);

                if(  string.IsNullOrEmpty(local) ||  ! locales.ContainsKey(local) )
                {
                    return PartialView("ErrorUsuarioLocal");
                }

                using (Ventas ventas = new Ventas())
                {
                    var data = ventas.VentasLocalPorVendedor(Empresa,anio, mes, local);

                    if (descarga)
                    {
                        this.Response.AddHeader("content-type", "application/vnd.ms-excel");
                        this.Response.AddHeader("content-disposition", string.Format("inline;filename=Ventas_Local_X_Vendedor-{0}_{1}-{2}.xls", local, anio, mes));
                    }

                    ViewBag.Descarga = descarga ? "Si" : "No";
                    return PartialView("VentasPorVendedor_Resultado", data);
                }


            }
            catch (Exception e)
            {

            }
            return PartialView("Error");
        }


        [HttpGet]
        [AuthorizeByRol]
        [MenuFilter]
        public ActionResult Vendedor()
        {

            Common commons = new Common();
            string vendedor = User_Helper.FlexUserName();

            ViewBag.locales = commons.SucursalesXUsuario(vendedor).Select(i => new SelectListItem() { Value = i.Key, Text = i.Value }).ToList();

            ViewBag.anio = commons.ListaAnios();
            ViewBag.meses = commons.ListaMeses();
            return View();
        }


        [HttpPost]
        [AuthorizeByRol]
        public ActionResult Vendedor(FormCollection form)
        {
            try
            {

                Common commons = new Common();
                var listaMeses = commons.ListaMeses();

                string vendedor = User_Helper.FlexUserName();

                string local = "";
                int anio = 0;
                string mes = "";
                bool descarga = false;

                int.TryParse(form["anio"], out anio);
                mes = form["mes"];
                local = form["local"];

                bool.TryParse(form["descarga"], out descarga);

                using (Ventas ventas = new Ventas())
                {
                    var data = ventas.Vendedor(vendedor, anio, mes);

                    ViewBag.U_Nombre = vendedor;
                    ViewBag.U_Sucursal = local;

                    ViewBag.D_Fecha = DateTime.Now.ToString("dd/MM/yyyy");
                    ViewBag.D_Anio = DateTime.Now.Year.ToString();
                    ViewBag.D_Anio_Anterior = (DateTime.Now.Year - 1).ToString();

                    ViewBag.D_Dia = DateTime.Now.Day.ToString();
                    ViewBag.D_Mes = DateTime.Now.Month.ToString();
                    string cmes = String.Format("{0:D2}", DateTime.Now.Month);

                    var mescx = listaMeses.Where<SelectListItem>(p => p.Value == cmes).Select(p => p.Text).FirstOrDefault();
                    if (mescx != null)
                    {
                        ViewBag.D_MesName = mescx;
                    }



                    ViewBag.S_Anio = anio.ToString();
                    ViewBag.S_Anio_Anterior = (anio - 1).ToString();

                    ViewBag.S_Mes = mes;
                    var mesx = listaMeses.Where<SelectListItem>(p => p.Value == mes).Select(p => p.Text).FirstOrDefault();
                    if(  mesx != null )
                    {
                        ViewBag.S_MesName = mesx;
                    }


                    ViewBag.C_TotalDia_Anterior = "";
                    ViewBag.C_TotalDia = "";
                    ViewBag.C_TotalMes_Anterior = "";
                    ViewBag.C_TotalMes = "";
                    ViewBag.S_TotalMes_Anterior = "";
                    ViewBag.S_TotalMes = "";


                    try { ViewBag.C_TotalDia_Anterior = data["Acumulado Mismo Mes Año Anterior"];  } catch (Exception e ) { }
                    try { ViewBag.C_TotalDia = data["Ventas Hoy"];  } catch (Exception e) { }
                    try { ViewBag.C_TotalMes_Anterior = data["Total Mensual Año Anterior"];  } catch (Exception e) { }
                    try { ViewBag.C_TotalMes = data["Acumulado del Mes"];  } catch (Exception e) { }
                    try { ViewBag.S_TotalMes_Anterior = data["Acumulado Periodo Seleccionado Año Anterior"];  } catch (Exception e) { }
                    try { ViewBag.S_TotalMes = data["Acumulado Periodo Seleccionado"];  } catch (Exception e) { }

                    if (descarga)
                    {
                        this.Response.AddHeader("content-type", "application/vnd.ms-excel");
                        this.Response.AddHeader("content-disposition", string.Format("inline;filename=Ventas_Vendedor_{0}_{1}-{2}.xls", vendedor,  anio, mes));
                    }

                    ViewBag.Descarga = descarga ? "Si" : "No";
                    return PartialView("Vendedor_Resultado", data);
                }


            }
            catch (Exception e)
            {

            }
            return PartialView("Error");
        }

    }
}

WebReportes/Views/Locales/Vendedor.cshtml
<section class="form-fields">
    <fieldset>
        @using (@Html.BeginForm("Vendedor", "Locales", FormMethod.Post, new { name = "Info" }))
        {
            @Html.Hidden("descarga", "")
            <div class="fld-row">

                <div class="fld  col-md-2">
                    @Html.DropDownList("anio", (List<SelectListItem>)ViewBag.anio, new { @class = "chosen-select", placeholder = "Seleccionar Año", @default = "2018" })
                </div>
                <div class="fld  col-md-2">
                    @Html.DropDownList("mes", (List<SelectListItem>)ViewBag.meses, new { @class = "chosen-select", placeholder = "Seleccionar Mes", @default = "07" })
                </div>

                <div class="fld  col-md-2">
                    @Html.DropDownList("local", (List<SelectListItem>)ViewBag.locales, new { @class = "chosen-select", placeholder = "Seleccionar Sucursal", })
                </div>

                <div class="fld col-md-4">
                    <input type="button" name="clear" value="Limpiar Datos" class="form_clear" data-form="Info" data-response="#form_response" />
                    <input type="button" name="submit" value="Generar Reporte" class="form_submit" data-form="Info" data-response="#form_response" />
                    <input type="button" name="export" value="Exportar Resultados" class="form_export" data-form="Info" />
                    <input type="button" name="fullscreen" value="Fullscreen" class="toggle_fullscreen" />
                    <input type="submit" name="enviar" value="Enviar" class="form_enviar" style="display:none;" />
                </div>


            </div>
        }

    </fieldset>
</section>
<section class="response_wrap_container">
    <div class="response_container">
        <div id="form_response"></div>
    </div>
</section>

WebReportes/Views/Locales/Vendedor_Resultado.cshtml
<table border="0" width="60%">

    <tr>
        <td>&nbsp;</td>
    </tr>


    <tr>
        <td width="100%">

            <table border="1" class="table-resumida" >
                <tr class="btn-info">
                    <th align="center" colspan="2">  <p> Usuario </p> </th>
                </tr>

                <tr class='impar' )>
                    <td align="left"> Nombre </td>
                    <td align="left"> @Html.Raw(ViewBag.U_Nombre) </td>
                </tr>

                <tr class='par' )>
                    <td align="left"> Sucursal </td>
                    <td align="left"> @Html.Raw(ViewBag.U_Sucursal) </td>
                </tr>

                <tr class='par' )>
                    <td align="left"> Fecha </td>
                    <td align="left"> @Html.Raw(ViewBag.D_Fecha) </td>
                </tr>

            </table>


        </td>
    </tr>


    <tr>
        <td>&nbsp;</td>
    </tr>


    <tr>
        <td width="100%">

            <table border="1" class="table-resumida" width="100%">
                <tr class="btn-info">
                    <th align="center" colspan="3">  <p>Periodo Actual</p> </th>
                </tr>

                <tr class="btn-info">
                    <th align="center">  <p>  @Html.Raw(ViewBag.D_MesName)</p> </th>
                    <th align="center">  <p> @Html.Raw(ViewBag.D_Anio_Anterior) </p> </th>
                    <th align="center">  <p> @Html.Raw(ViewBag.D_Anio) </p> </th>
                </tr>


                <tr class='impar' )>
                    <td align="left"> Total Mes al dia @Html.Raw(ViewBag.D_Dia) </td>
                    <td align="right" class="Number"> @Html.Raw(ViewBag.C_TotalDia_Anterior) </td>
                    <td align="right" class="Number"> @Html.Raw(ViewBag.C_TotalDia) </td>
                </tr>

                <tr class='par' )>
                    <td align="left"> Total Mes </td>
                    <td align="right"  class="Number"> @Html.Raw(ViewBag.C_TotalMes_Anterior) </td>
                    <td align="right"  class="Number"> @Html.Raw(ViewBag.C_TotalMes) </td>
                </tr>

            </table>

        </td>
    </tr>




    @if (!string.IsNullOrEmpty(ViewBag.S_TotalMes))
    {


        <tr>
            <td>&nbsp;</td>
        </tr>

        <tr>
            <td>

                <table border="1" class="table-resumida" width="100%">
                    <tr class="btn-info">
                        <th align="center" colspan="3">  <p>Periodo Seleccionado </p> </th>
                    </tr>

                    <tr class="btn-info">
                        <th align="center">  <p> @Html.Raw(ViewBag.S_MesName)</p> </th>
                        <th align="center">  <p> @Html.Raw(ViewBag.S_Anio_Anterior) </p> </th>
                        <th align="center">  <p> @Html.Raw(ViewBag.S_Anio) </p> </th>
                    </tr>


                    <tr class='impar' )>
                        <td align="left"> Total Ventas  </td>
                        <th align="center"  class="Number">  <p> @Html.Raw(ViewBag.S_TotalMes_Anterior) </p> </th>
                        <th align="center"  class="Number">  <p> @Html.Raw(ViewBag.S_TotalMes) </p> </th>
                    </tr>

                </table>

            </td>
        </tr>
    }

    <tr>
        <td>&nbsp;</td>
    </tr>


</table>

WebReportes/Views/Locales/VentasPorVendedor.cshtml
<section class="form-fields">
    <fieldset>
        @using (@Html.BeginForm("VentasPorVendedor", "Locales", FormMethod.Post, new { name = "Info" }))
        {
            @Html.Hidden("descarga", "")
            @Html.Hidden("sucursales", "")
            <div class="fld-row">

                <div class="fld  col-md-2">
                    @Html.DropDownList("anio", (List<SelectListItem>)ViewBag.anio, new { @class = "chosen-select", placeholder = "Seleccionar Año", @default = "2018" })
                </div>
                <div class="fld  col-md-2">
                    @Html.DropDownList("mes", (List<SelectListItem>)ViewBag.meses, new { @class = "chosen-select", placeholder = "Seleccionar Mes", @default = "07" })
                </div>

                <div class="fld  col-md-2">
                    @Html.DropDownList("local", (List<SelectListItem>)ViewBag.locales, new { @class = "chosen-select", placeholder = "Seleccionar Sucursal", })
                </div>

                <div class="fld col-md-4">
                    <input type="button" name="clear" value="Limpiar Datos" class="form_clear" data-form="Info" data-response="#form_response" />
                    <input type="button" name="submit" value="Generar Reporte" class="form_submit" data-form="Info" data-response="#form_response" />
                    <input type="button" name="export" value="Exportar Resultados" class="form_export" data-form="Info" />
                    <input type="button" name="fullscreen" value="Fullscreen" class="toggle_fullscreen" />
                    <input type="submit" name="enviar" value="Enviar" class="form_enviar" style="display:none;" />
                </div>


            </div>
        }

    </fieldset>
</section>
<section class="response_wrap_container">
    <div class="response_container">
        <div id="form_response"></div>
    </div>
</section>

WebReportes/Views/Locales/VentasPorVendedor_Resultado.cshtml
@model IEnumerable<Dictionary<string, string>>


@if (Model.Count() > 1)
{
    int tr_par = 1, td_par = 1;
    var useclass = "";


    <table border="1" class="table-resumida">

        <tr class="btn-info">
            <th align="center">  <p>Vendedor</p> </th>
            <th align="center">  <p>Venta Dia</p> </th>
            <th align="center">  <p>Venta Año Anterior</p> </th>
            <th align="center">  <p>Acumulado </p></th>
            <th align="center">  <p>Acumulado Año Anterior</p></th>

            <th align="center">  <p>Total Año Anterior</p></th>
            <th align="center">   </th>
            <th align="center">  <p>Acumulado Mes X </p></th>
            <th align="center">  <p>Acumulado Año Mes X Anterior</p> </th>

        </tr>

        @foreach (var row in Model)
        {
                useclass = (tr_par++ % 2 == 0 ? "par" : "impar");

            <tr @Html.Raw("class='" + useclass + "'")>
                <td> @Html.Raw(row["Vendedor"]) </td>
                <td class="Number" align="right"> @Html.Raw(row["Diario"]) </td>
                <td class="Number" align="right"> @Html.Raw(row["DiarioAnterior"]) </td>
                <td class="Number" align="right"> @Html.Raw(row["Acumulado"]) </td>
                <td class="Number" align="right"> @Html.Raw(row["AcumuladoAnterior"]) </td>
                <td class="Number" align="right"> @Html.Raw(row["TotalAnterior"]) </td>
                <td></td>
                <td class="Number" align="right"> @Html.Raw(row["Acumulado2"]) </td>
                <td class="Number" align="right"> @Html.Raw(row["AcumuladoAnterior2"]) </td>

            </tr>
        }

    </table>

}
else
{
    <div class=""> No hay resultados disponibles.</div>
}