WebReportes/Controllers/IngresosController.cs
using Servicio;
using System.Collections.Generic;
using System.Web.Mvc;
using System.Linq;
using System;
using WebReportes.Helpers;
using WebReportes.Utils;

namespace WebReportes.Controllers
{
    [Authorize]
    public class IngresosController : Controller
    {


        #region Ventas Contabilidad

            [HttpGet]
            [AuthorizeByRol]
            [MenuFilter]
            public ActionResult Pagos()
            {
                string Empresa = SessionEx.Get(SessionEx.eCommerce);


                Ingresos ingresos = new Ingresos();

                var tiposDePago = ingresos.TiposDePago(Empresa);
                ViewBag.codigopago = tiposDePago.Select(i => new SelectListItem() { Value = i.Key, Text = i.Value }).ToList();

                var canal = ingresos.TiposDeCanales(Empresa);
                ViewBag.canal = canal.Select(i => new SelectListItem() { Value = i.Key, Text = i.Value }).ToList();



                Common commons = new Common();
                var sucursales = commons.SucursalesXEmpresa(Empresa);

                ViewBag.sucursales = sucursales.Select(i => new SelectListItem() { Value = i.Key, Text = i.Value }).ToList();

                ViewBag.anio = commons.ListaAnios() ;
                ViewBag.meses = commons.ListaMeses();

                ViewBag.dias = commons.ListaDias();


                return View();
            }


            [HttpPost]
            [AuthorizeByRol]
            public ActionResult Pagos(FormCollection form)
            {
                try
                {
                    string Empresa = SessionEx.Get(SessionEx.eCommerce);

                    int anio = 0;
                    string mes = "";
                    string dia = "";
                    string sucursales = "";
                    string codigopago = "";
                    string canal = "";
                    bool descarga = false;

                    int.TryParse(form["anio"], out anio);
                    mes = form["mes"];
                    dia = form["dia"];

                    sucursales = form["sucursales"];
                    codigopago = form["pago"];
                    canal = form["canal"];

                    bool.TryParse(form["descarga"], out descarga);

                    using (Ingresos ingresos = new Ingresos())
                    {
                        var data = ingresos.Ventas(Empresa, anio, mes, dia, sucursales, codigopago, canal);

                        if (descarga)
                        {
                            this.Response.AddHeader("content-type", "application/vnd.ms-excel");
                            this.Response.AddHeader("content-disposition", string.Format("inline;filename=Ingresos_Pagos_{0}-{1}-{2}.xls", Empresa, anio, mes));
                        }

                        return PartialView("Pagos_Resultado", data);
                    }


                }
                catch (Exception e)
                {

                }
                return PartialView("Error");
            }


        #endregion



        #region Ventas Control


            [HttpGet]
            [AuthorizeByRol]
            [MenuFilter]
            public ActionResult Control()
            {
                string Empresa = SessionEx.Get(SessionEx.eCommerce);
                Ingresos ingresos = new Ingresos();

                var bodegas = ingresos.Bodegas(Empresa);
                ViewBag.bodegas = bodegas.Select(i => new SelectListItem() { Value = i.Key, Text = i.Value }).ToList();

                var canal = ingresos.TiposDeCanales(Empresa);
                ViewBag.canal = canal.Select(i => new SelectListItem() { Value = i.Key, Text = i.Value }).ToList();



                Common commons = new Common();
                var sucursales = commons.SucursalesXEmpresa(Empresa);

                ViewBag.sucursales = sucursales.Select(i => new SelectListItem() { Value = i.Key, Text = i.Value }).ToList();

                ViewBag.anio = commons.ListaAnios();
                ViewBag.meses = commons.ListaMeses();
                ViewBag.dias = commons.ListaDias();

                return View();
            }


            [HttpPost]
            [AuthorizeByRol]
            public ActionResult Control(FormCollection form)
            {
                try
                {
                    string Empresa = SessionEx.Get(SessionEx.eCommerce);
                    int anio = 0;
                    string mes = "";
                    string dia = "";
                    string sucursales = "";
                    string bodega = "";
                    string canal = "";
                    bool descarga = false;

                    int.TryParse(form["anio"], out anio);
                    mes = form["mes"];
                    dia = form["dia"];
                    sucursales = form["sucursales"];
                    bodega = form["bodega"];
                    canal = form["canal"];

                    bool.TryParse(form["descarga"], out descarga);

                    using (Ingresos ingresos = new Ingresos())
                    {
                        var data = ingresos.Ventas_Control(Empresa, anio, mes, dia, sucursales, bodega, canal);

                        if (descarga)
                        {
                            this.Response.AddHeader("content-type", "application/vnd.ms-excel");
                            this.Response.AddHeader("content-disposition", string.Format("inline;filename=Ingresos_Control_{0}-{1}-{2}.xls", Empresa, anio, mes));
                        }

                        return PartialView("Control_Resultado", data);
                    }


                }
                catch (Exception e)
                {

                }
                return PartialView("Error");
            }


        #endregion


    }
}

WebReportes/Views/Ingresos/Control.cshtml
<section class="form-fields">
    <fieldset>
        @using (@Html.BeginForm("Control", "Ingresos", FormMethod.Post, new { name = "Info" }))
        {
            @Html.Hidden("descarga", "")
            @Html.Hidden("sucursales", "")
            <div class="fld-row">

                <div class="fld  col-md-2">
                    @Html.DropDownList("anio", (List<SelectListItem>)ViewBag.anio, new { @class = "chosen-select", placeholder = "Seleccionar Año", @default = "2018" })
                </div>
                <div class="fld  col-md-2">
                    @Html.DropDownList("mes", (List<SelectListItem>)ViewBag.meses, new { @class = "chosen-select", placeholder = "Seleccionar Mes", @default = "07" })
                </div>

                <div class="fld  col-md-1">
                    @Html.DropDownList("dia", (List<SelectListItem>)ViewBag.dias, new { @class = "chosen-select", placeholder = "Seleccionar Dia", @default = "01" })
                </div>

                <div class="fld  col-md-4">
                    @Html.DropDownList("sucursales_list", (List<SelectListItem>)ViewBag.sucursales, new { @class = "chosen-select-multiple", multiple = "multiple", resumeto = "#sucursales" })
                </div>

                <div class="fld  col-md-2">
                    @Html.DropDownList("bodega", (List<SelectListItem>)ViewBag.bodegas, new { @class = "chosen-select", placeholder = "Seleccionar Bodega", @default = "" })
                </div>                

                <div class="fld  col-md-2">
                    @Html.DropDownList("canal", (List<SelectListItem>)ViewBag.canal, new { @class = "chosen-select", placeholder = "Seleccionar Canal", @default = "" })
                </div>

                <div class="fld col-md-4">
                    <input type="button" name="clear" value="Limpiar Datos" class="form_clear" data-form="Info" data-response="#form_response" />
                    <input type="button" name="submit" value="Generar Reporte" class="form_submit" data-form="Info" data-response="#form_response" />
                    <input type="button" name="export" value="Exportar Resultados" class="form_export" data-form="Info" />
                    <input type="button" name="fullscreen" value="Fullscreen" class="toggle_fullscreen" />
                    <input type="submit" name="enviar" value="Enviar" class="form_enviar" style="display:none;" />
                </div>


            </div>        
        }

    </fieldset>
</section>
<section class="response_wrap_container">
    <div class="response_container">
        <div id="form_response"></div>
    </div>
</section>

WebReportes/Views/Ingresos/ControlWH.cshtml
<section class="form-fields">
    <fieldset>
        @using (@Html.BeginForm("ControlWH", "Ingresos", FormMethod.Post, new { name = "Info" }))
        {
            @Html.Hidden("descarga", "")
            @Html.Hidden("sucursales", "")
            <div class="fld-row">

                <div class="fld  col-md-2">
                    @Html.DropDownList("anio", (List<SelectListItem>)ViewBag.anio, new { @class = "chosen-select", placeholder = "Seleccionar Año", @default = "2018" })
                </div>
                <div class="fld  col-md-2">
                    @Html.DropDownList("mes", (List<SelectListItem>)ViewBag.meses, new { @class = "chosen-select", placeholder = "Seleccionar Mes", @default = "07" })
                </div>

                <div class="fld  col-md-1">
                    @Html.DropDownList("dia", (List<SelectListItem>)ViewBag.dias, new { @class = "chosen-select", placeholder = "Seleccionar Dia", @default = "01" })
                </div>

                <div class="fld  col-md-4">
                    @Html.DropDownList("sucursales_list", (List<SelectListItem>)ViewBag.sucursales, new { @class = "chosen-select-multiple", multiple = "multiple", resumeto = "#sucursales" })
                </div>

                <div class="fld  col-md-2">
                    @Html.DropDownList("bodega", (List<SelectListItem>)ViewBag.bodegas, new { @class = "chosen-select", placeholder = "Seleccionar Bodega", @default = "" })
                </div>

                <div class="fld  col-md-2">
                    @Html.DropDownList("canal", (List<SelectListItem>)ViewBag.canal, new { @class = "chosen-select", placeholder = "Seleccionar Canal", @default = "" })
                </div>

                <div class="fld col-md-4">
                    <input type="button" name="clear" value="Limpiar Datos" class="form_clear" data-form="Info" data-response="#form_response" />
                    <input type="button" name="submit" value="Generar Reporte" class="form_submit" data-form="Info" data-response="#form_response" />
                    <input type="button" name="export" value="Exportar Resultados" class="form_export" data-form="Info" />
                    <input type="button" name="fullscreen" value="Fullscreen" class="toggle_fullscreen" />
                    <input type="submit" name="enviar" value="Enviar" class="form_enviar" style="display:none;" />
                </div>


            </div>
        }

    </fieldset>
</section>
<section class="response_wrap_container">
    <div class="response_container">
        <div id="form_response"></div>
    </div>
</section>

WebReportes/Views/Ingresos/ControlWH_Resultado.cshtml
@using WebReportes.Helpers
@model IEnumerable<Dictionary<string, string>>

@if (Model.Count() > 1)
{
    var datos = Model.ToList();
    int tr_par = 1;
    var useclass = "";
    var old_local = "";

    <table border="1" class="table-resumida">
        <tr>
            <th align="center">  Local </th>
            <th align="center">  Tipo Documento </th>
            <th align="center">  Numero Documento </th>
            <th align="center">  Monto </th>
            <th align="center">  Fecha </th>
            <th align="center">  Bodega </th>
            <th align="center">  Vigencia </th>
            <th align="center">  Emitido </th>
            <th align="center">  Vendedor </th>
            <th align="center">  Razon Social </th>
        </tr>

        @foreach (var row in datos)
        {
            if (row.Count() > 1)
            {
                useclass = (tr_par++ % 2 == 0 ? "par" : "impar");

                <tr @Html.Raw("class='" + useclass + "'")>
                    <td align="left" @Html.Raw("class='" + useclass + "'")>  TOTALES @Html.Raw(row["Local"])</td>
                    <td align="right" @Html.Raw("class='" + useclass + "'")>  @Html.Raw(row["TipoDocto"]) </td>
                    <td align="left" @Html.Raw("class='" + useclass + "'")>   @User_Helper.Documento(row["TipoDocto"], row["Numero"])   </td>
                    <td align="right" @Html.Raw("class='Number " + useclass + "'")>  @Html.Raw(row["Monto"]) </td>
                    <td align="left" @Html.Raw("class='" + useclass + "'")>  @Html.Raw(row["Fecha"]) </td>
                    <td align="left" @Html.Raw("class='" + useclass + "'")>  @Html.Raw(row["Bodega"]) </td>
                    <td align="center" @Html.Raw("class='" + useclass + "'")>  @Html.Raw(row["Vigencia"]) </td>
                    <td align="center" @Html.Raw("class='" + useclass + "'")>  @Html.Raw(row["Emitido"]) </td>
                    <td align="left" @Html.Raw("class='" + useclass + "'")>  @Html.Raw(row["Vendedor"]) </td>
                    <td align="left" @Html.Raw("class='" + useclass + "'")>  @Html.Raw(row["RazonSocial"]) </td>
                </tr>

            }
        }

    </table>
}
else
{
    <div class=""> No hay resultados disponibles.</div>
}

WebReportes/Views/Ingresos/Control_Resultado.cshtml
@using WebReportes.Helpers
@model IEnumerable<Dictionary<string, string>>

@if (Model.Count() > 1)
{
    var datos = Model.ToList();
    int tr_par = 1;
    var useclass = "";
    var old_local = "";

    <table border="1" class="table-resumida">

        <tr>
            <th align="center">  Local </th>
            <th align="center">  Tipo Documento </th>
            <th align="center">  Numero Documento </th>
            <th align="center">  Monto </th>
            <th align="center">  Fecha </th>
            <th align="center">  Bodega </th>
            <th align="center">  Vigencia </th>
            <th align="center">  Emitido </th>
            <th align="center">  Vendedor </th>
            <th align="center">  Razon Social </th>
        </tr>

        @foreach (var row in datos)
        {
            if (row.Count() > 1)
            {
                useclass = (tr_par++ % 2 == 0 ? "par" : "impar");

                <tr @Html.Raw("class='" + useclass + "'")>
                    <td align="left" @Html.Raw("class='" + useclass + "'")>  TOTALES @Html.Raw(row["Local"])</td>
                    <td align="right" @Html.Raw("class='" + useclass + "'")>  @Html.Raw(row["TipoDocto"]) </td>
                    <td align="left" @Html.Raw("class='" + useclass + "'")>   @User_Helper.Documento(row["TipoDocto"], row["Numero"])   </td>
                    <td align="right" @Html.Raw("class='Number " + useclass + "'")>  @Html.Raw(row["Monto"]) </td>
                    <td align="left" @Html.Raw("class='" + useclass + "'")>  @Html.Raw(row["Fecha"]) </td>
                    <td align="left" @Html.Raw("class='" + useclass + "'")>  @Html.Raw(row["Bodega"]) </td>
                    <td align="center" @Html.Raw("class='" + useclass + "'")>  @Html.Raw(row["Vigencia"]) </td>
                    <td align="center" @Html.Raw("class='" + useclass + "'")>  @Html.Raw(row["Emitido"]) </td>
                    <td align="left" @Html.Raw("class='" + useclass + "'")>  @Html.Raw(row["Vendedor"]) </td>
                    <td align="left" @Html.Raw("class='" + useclass + "'")>  @Html.Raw(row["RazonSocial"]) </td>
                </tr>

            }
        }
    </table>
}
else
{
    <div class=""> No hay resultados disponibles.</div>
}

WebReportes/Views/Ingresos/Pagos.cshtml
<section class="form-fields">
    <fieldset>
        @using (@Html.BeginForm("Pagos", "Ingresos", FormMethod.Post, new { name = "Info" }))
        {
            @Html.Hidden("descarga", "")
            @Html.Hidden("sucursales", "")
            <div class="fld-row">

                <div class="fld  col-md-2">
                    @Html.DropDownList("anio", (List<SelectListItem>)ViewBag.anio, new { @class = "chosen-select", placeholder = "Seleccionar Año", @default = "2018" })
                </div>
                <div class="fld  col-md-2">
                    @Html.DropDownList("mes", (List<SelectListItem>)ViewBag.meses, new { @class = "chosen-select", placeholder = "Seleccionar Mes", @default = "07" })
                </div>

                <div class="fld  col-md-1">
                    @Html.DropDownList("dia", (List<SelectListItem>)ViewBag.dias, new { @class = "chosen-select", placeholder = "Seleccionar Dia", @default = "01" })
                </div>

                <div class="fld  col-md-4">
                    @Html.DropDownList("sucursales_list", (List<SelectListItem>)ViewBag.sucursales, new { @class = "chosen-select-multiple", multiple = "multiple", resumeto = "#sucursales" })
                </div>

                <div class="fld  col-md-2">
                    @Html.DropDownList("pago", (List<SelectListItem>)ViewBag.codigopago, new { @class = "chosen-select", placeholder = "Seleccionar Tipo Pago", @default = "" })
                </div>                

                <div class="fld  col-md-2">
                    @Html.DropDownList("canal", (List<SelectListItem>)ViewBag.canal, new { @class = "chosen-select", placeholder = "Seleccionar Canal", @default = "" })
                </div>

                <div class="fld col-md-4">
                    <input type="button" name="clear" value="Limpiar Datos" class="form_clear" data-form="Info" data-response="#form_response" />
                    <input type="button" name="submit" value="Generar Reporte" class="form_submit" data-form="Info" data-response="#form_response" />
                    <input type="button" name="export" value="Exportar Resultados" class="form_export" data-form="Info" />
                    <input type="button" name="fullscreen" value="Fullscreen" class="toggle_fullscreen" />
                    <input type="submit" name="enviar" value="Enviar" class="form_enviar" style="display:none;" />
                </div>


            </div>        
        }

    </fieldset>
</section>
<section class="response_wrap_container">
    <div class="response_container">
        <div id="form_response"></div>
    </div>
</section>

WebReportes/Views/Ingresos/PagosWH.cshtml
<section class="form-fields">
    <fieldset>
        @using (@Html.BeginForm("PagosWH", "Ingresos", FormMethod.Post, new { name = "Info" }))
        {
            @Html.Hidden("descarga", "")
            @Html.Hidden("sucursales", "")
            <div class="fld-row">

                <div class="fld  col-md-2">
                    @Html.DropDownList("anio", (List<SelectListItem>)ViewBag.anio, new { @class = "chosen-select", placeholder = "Seleccionar Año", @default = "2018" })
                </div>
                <div class="fld  col-md-2">
                    @Html.DropDownList("mes", (List<SelectListItem>)ViewBag.meses, new { @class = "chosen-select", placeholder = "Seleccionar Mes", @default = "07" })
                </div>

                <div class="fld  col-md-1">
                    @Html.DropDownList("dia", (List<SelectListItem>)ViewBag.dias, new { @class = "chosen-select", placeholder = "Seleccionar Dia", @default = "01" })
                </div>

                <div class="fld  col-md-4">
                    @Html.DropDownList("sucursales_list", (List<SelectListItem>)ViewBag.sucursales, new { @class = "chosen-select-multiple", multiple = "multiple", resumeto = "#sucursales" })
                </div>

                <div class="fld  col-md-2">
                    @Html.DropDownList("pago", (List<SelectListItem>)ViewBag.codigopago, new { @class = "chosen-select", placeholder = "Seleccionar Tipo Pago", @default = "" })
                </div>

                <div class="fld  col-md-2">
                    @Html.DropDownList("canal", (List<SelectListItem>)ViewBag.canal, new { @class = "chosen-select", placeholder = "Seleccionar Canal", @default = "" })
                </div>

                <div class="fld col-md-4">
                    <input type="button" name="clear" value="Limpiar Datos" class="form_clear" data-form="Info" data-response="#form_response" />
                    <input type="button" name="submit" value="Generar Reporte" class="form_submit" data-form="Info" data-response="#form_response" />
                    <input type="button" name="export" value="Exportar Resultados" class="form_export" data-form="Info" />
                    <input type="button" name="fullscreen" value="Fullscreen" class="toggle_fullscreen" />
                    <input type="submit" name="enviar" value="Enviar" class="form_enviar" style="display:none;" />
                </div>


            </div>
        }

    </fieldset>
</section>
<section class="response_wrap_container">
    <div class="response_container">
        <div id="form_response"></div>
    </div>
</section>

WebReportes/Views/Ingresos/PagosWH_Resultado.cshtml
@using WebReportes.Helpers
@model IEnumerable<Dictionary<string, string>>

@if (Model.Count() > 1)
{
    var datos = Model.ToList();
    int tr_par = 1;
    var useclass = "";
    var old_local = "";

    <table border="1" class="table-resumida">

        <tr>
            <th align="center">  Local </th>
            <th align="center">  Tipo Documento </th>
            <th align="center">  Numero Documento </th>
            <th align="center">  Monto </th>
            <th align="center">  Fecha </th>
            <th align="center">  Tipo Pago </th>
            <th align="center">  Dcto Pago  </th>
            <th align="center">  Razon Social </th>
        </tr>

        @foreach (var row in datos)
        {
            if (row.Count() > 1)
            {
                useclass = (tr_par++ % 2 == 0 ? "par" : "impar");

                <tr @Html.Raw("class='" + useclass + "'")>
                    <td align="right" @Html.Raw("class='" + useclass + "'")>  TOTALES @Html.Raw(row["Local"])</td>
                    <td align="right" @Html.Raw("class='" + useclass + "'")>  @Html.Raw(row["TipoDocto"]) </td>
                    <td align="left" @Html.Raw("class='" + useclass + "'")>   @User_Helper.Documento(row["TipoDocto"], row["Numero"])   </td>
                    <td align="right" @Html.Raw("class='Number " + useclass + "'")>  @Html.Raw(row["Monto"]) </td>
                    <td align="right" @Html.Raw("class='" + useclass + "'")>  @Html.Raw(row["Fecha"]) </td>
                    <td align="right" @Html.Raw("class='" + useclass + "'")>  @Html.Raw(row["CodigoPago"]) </td>
                    <td align="right" @Html.Raw("class='" + useclass + "'")>  @Html.Raw(row["NroDoctoPago"]) </td>
                    <td align="right" @Html.Raw("class='" + useclass + "'")>  @Html.Raw(row["RazonSocial"]) </td>
                </tr>

            }
        }
    </table>
}
else
{
    <div class=""> No hay resultados disponibles.</div>
}

WebReportes/Views/Ingresos/Pagos_Resultado.cshtml
@using WebReportes.Helpers
@model IEnumerable<Dictionary<string, string>>

@if (Model.Count() > 1)
{
    var datos = Model.ToList();
    int tr_par = 1;
    var useclass = "";
    var old_local = "";

    <table border="1" class="table-resumida">

        <tr>
            <th align="center">  Local </th>
            <th align="center">  Tipo Documento </th>
            <th align="center">  Numero Documento </th>
            <th align="center">  Monto </th>
            <th align="center">  Fecha </th>
            <th align="center">  Tipo Pago </th>
            <th align="center">  Dcto Pago  </th>
            <th align="center">  Razon Social </th>
        </tr>

        @foreach (var row in datos)
        {
            if (row.Count() > 1)
            {
                useclass = (tr_par++ % 2 == 0 ? "par" : "impar");

                <tr @Html.Raw("class='" + useclass + "'")>
                    <td align="right" @Html.Raw("class='" + useclass + "'")>  TOTALES @Html.Raw(row["Local"])</td>
                    <td align="right" @Html.Raw("class='" + useclass + "'")>  @Html.Raw(row["TipoDocto"]) </td>
                    <td align="left" @Html.Raw("class='" + useclass + "'")>   @User_Helper.Documento(row["TipoDocto"], row["Numero"])   </td>
                    <td align="right" @Html.Raw("class='Number " + useclass + "'")>  @Html.Raw(row["Monto"]) </td>
                    <td align="right" @Html.Raw("class='" + useclass + "'")>  @Html.Raw(row["Fecha"]) </td>
                    <td align="right" @Html.Raw("class='" + useclass + "'")>  @Html.Raw(row["CodigoPago"]) </td>
                    <td align="right" @Html.Raw("class='" + useclass + "'")>  @Html.Raw(row["NroDoctoPago"]) </td>
                    <td align="right" @Html.Raw("class='" + useclass + "'")>  @Html.Raw(row["RazonSocial"]) </td>
                </tr>

            }
        }
    </table>
}
else
{
    <div class=""> No hay resultados disponibles.</div>
}